## global definitions
# k8s:
#   provider: 'libvirt'             ## two options 'libvirt' or 'virtualbox'#######################################
#   domain: 'k8s.local'
#   ip_start: 192.168.121.128       ## This is required for libvirt provider to create a subnet ###################
#   ip_end: 192.168.121.254         ## for virtualbox its use the default vboxnet0 ################################
#   ncpnd: 1                        ## number of master nodes, load balancer will balanced the traffic to kubeapi##
#   nwrknd: 2                       ## number of worker nodes #####################################################
#   cni: "default"                  ## 3 options 'default'(simple routing & no 3rd party CNI),'calico','cilium' ###
#   V: 1.22                         ## k8s version ################################################################
#   CRI_CTL_V: 1.25                 ## CRI version ################################################################
#   RUNC_V: 1.1                     ## runc version ###############################################################
#   CRUN_V: 1.7                     ## Any one entry will work either RUNC or CRUN
#   CONTD_V: 1.6                    ## containerd version #########################################################
#   CNI_PLUGIN_V: 1.1               ## cni plugin version #########################################################
#   build_directory: "<path>"       ## path to the directory where you downloaded & build all k8s related source ## 
# node:                             ## any node attrebutes can be configured here #################################      
#   private_key_name: "<ssh_key>"   ## ssh key name to ssh into the nodes,expect key in default ~/.ssh path #######

k8s:
  provider: "libvirt"
  domain: "k8s.local"
  ip_start: 192.168.121.128
  ip_end: 192.168.121.254
  ncpnd: 1
  nwrknd: 1
  cni: "default"
  V: 1.25
  CRI_CTL_V: 1.25
  CONTD_V: 1.6
  CNI_PLUGIN_V: 1.1
  build_directory: "path/to/build_directory"
  CRUN_V: 1.7
node:
  private_key_name: "ssh_key_name"
  os: "generic/ubuntu2204"

