---
- hosts: "{{ host_name }}"
  become: true
  tasks:
  
    - name: Updating hostname and nameservers
      command: "{{ item }}"
      with_items:
      - hostnamectl set-hostname {{ host_name }}
      - apt install net-tools -y
